### ISSUE TITLE
Clarify who to contact for maintainance

### ISSUE THREAD

**Issue by niccokunzmann** [spaceapi-community/my-hackerspace#14]
It is only mentioned that coredump people maintain this. If that is mentioned, I would like to add behind this the usernames of the maintainers and if they would like to be mentioned. This also allows communication in the old repo where I can tag the new maintainers about things and be sure they are notified.

**Comment by niccokunzmann** [comment]
I would still like to know who to contact. Also, I think, I am happy to co-maintain this.

**Comment by FriederHannenheim** [comment]
The maintainer hasn't committed anything in 15 days but is still active on Github otherwise. We might need to fork again. I would really like for this project to continue since it's really useful to me

**Comment by niccokunzmann** [comment]
@FriederHannenheim I would not fork it, yet - maybe after 15 more days of inactivity. We can contact the maintainer, please mention the maintainer here and we can ask to get permission to work on this and review each other's pull requests. What do you think?

**Comment by FriederHannenheim** [comment]
@niccokunzmann yeah that sounds reasonable. @dbrgn

**Comment by dbrgn** [comment]
> hasn't committed anything in 15 days

Folks, this is an open source project. "Maintainer hasn't committed in 15 days" is a terrible metric. People have other obligations besides maintaining open source projects. I do get issue notifications, but my e-mail inbox is growing every day and I don't always have time to react immediately.

Right now the app is primarily maintained by me. Contributions are welcome, and once a few PRs have been submitted that look good, I can happily add that person as a co-maintainer.

You can also join the Matrix chat at `#spaceapi:matrix.coredump.ch`.

**Comment by dbrgn** [comment]
Actually I have to correct the comment above: I just now noticed that there are a few open pull requests and that I never got notifications for them (or the new issues). Looks like for some reason my notification settings were set to "participating only". I fixed that, so from now on I should see (and react) to submissions more quickly.

**Comment by niccokunzmann** [comment]
@dbrgn Thanks! I am a maintainer myself :) I guessed that something was keeping you away and it is normal that it takes long.
I joined #spaceapi:matrix.coredump.ch. Thanks for the link!
