### ISSUE TITLE
App crashed OpenLauncher

### ISSUE THREAD

**Issue by niccokunzmann** [spaceapi-community/my-hackerspace#31]
I can crash OpenLauncher with this. Here is the issue and the fix suggested:

https://github.com/OpenLauncherTeam/openlauncher/issues/692#issuecomment-1236296682

> I think that it is not a bug in OpenLauncher but in myhackerspace. Widget configuration activity must declare android:exported="true" in its AndroidManifest.xml.

**Comment by dbrgn** [comment]
Makes sense, will fix it.
