### ISSUE TITLE
display lastchange timestamp as formatted string

### ISSUE THREAD

**Issue by NANASHI0X74** [spaceapi-community/my-hackerspace#46]
Hi, I've discovered this app today and it's quite handy, but I wish that it would display the lastchange unix timestamp (for the status) in a more human-readable datetime format, preferably with both absolute and relative specifications (i.e. <dd-mm-yyyy, hh:mm> (<x hours ago | y days ago etc>)

**Comment by dbrgn** [comment]
Should become possible through https://github.com/spaceapi-community/spaceapi-kt/pull/36.
