### ISSUE TITLE
Release package on f-droid outdated

### ISSUE THREAD

**Issue by es-ka** [spaceapi-community/my-hackerspace#7]
f-droid provides version 1.8.2 which was released in 2016:
https://f-droid.org/de/packages/ch.fixme.status/

Would be nice to have a current 2.0 in f-droid repo ;-)

**Comment by dbrgn** [comment]
WIP:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11468
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11526

**Comment by niccokunzmann** [comment]
It is on the website, now: https://f-droid.org/en/packages/io.spaceapi.community.myhackerspace/

**Comment by es-ka** [comment]
Tanks a lot! Works as expected.
